### PR TITLE
Micronaut Metrics exporter for Influx, Datadog and Elastic

### PR DESCRIPTION
**Pull request by thiagolocatelli**
I have created three more modules, with the configuration and factory classes along with spock specifications for each.

- micrometer-registry-datadog
- micrometer-registry-elastic
- micrometer-registry-influx

The documentation has also been updated, to also look a little better.

```
introduction: Introduction
metricsEndpoint: Metrics Endpoint
metricsConcepts: Metrics Concepts
metricsAndReporters:
  title: Metrics Registries & Reporters
  metricsAndReportersAtlas: Atlas Registry
  metricsAndReportersCloudWatch: CloudWatch Registry
  metricsAndReportersDatadog: Datadog Registry
  metricsAndReportersElastic: Elastic Registry
  metricsAndReportersGraphite: Graphite Registry
  metricsAndReportersInflux: InfluxDB Registry
  metricsAndReportersPrometheus: Prometheus Registry
  metricsAndReportersStatsD: StatsD Registry
```

### CODE REVIEW

**Comment by graemerocher** [comment]
Awesome! Thank you so much. Only change I would make would be to add `@since 1.2.0` to each javadoc since this will go into the 1.2.0 release.

**Comment by thiagolocatelli** [comment]
@graemerocher going to apply the @since now. Thank you

**Comment by thiagolocatelli** [comment]
Done. When I have more time, I will include the rest of the metric registries from Micrometer. I need to go back to the Vault integration, my PR is failing.

**Comment by graemerocher** [comment]
Thanks for the contribution!

**Pull request merged**
