### PR TITLE
Use micronaut aws cloudwatch client instead of default one

### PR DESCRIPTION
**Pull request by n0tl3ss**
Use micronaut aws client instead of default one. In this way client configuration can be applied to CloudWatch client. Ex: proxy

### CODE REVIEW

**Comment by wetted** [comment]
> > I know this is a factory class but also changing the client should follow semantic versioning I think, and be in the next minor release, not patch.
> 
> Should I change SNAPSHOT version to `5.3.0-SNAPSHOT`?

I think what you need to do is that, but also create a 5.2.x branch off master. But I'll defer to @sdelamo: is that right?

**Review by wetted — CHANGES_REQUESTED** [review]
Please create a 5.2.x branch off master and bump the version for this PR to the next minor (5.3.0-SNAPSHOT).

**Review by wetted — APPROVED** [review]

**Comment by n0tl3ss** [comment]
> Please create a 5.2.x branch off master and bump the version for this PR to the next minor (5.3.0-SNAPSHOT).

https://github.com/micronaut-projects/micronaut-micrometer/tree/5.2.x
Changed version to `5.3.0-SNAPSHOT`

**Review by wetted — APPROVED** [review]

**Comment by sdelamo** [comment]
@n0tl3ss lets use "Squash Merge" when possible please.

**Pull request merged**
