### PR TITLE
New relic telemetry micrometer registry

### PR DESCRIPTION
**Pull request by alvarosanchez**

### CODE REVIEW

**Comment by StephanePaulus** [comment]
Hi @alvarosanchez  and @mparlee thanks for working on this, it will help me out too. 
@alvarosanchez will a SNAPSHOT or a new release be available soon?

**Comment by alvarosanchez** [comment]
Snapshots are published automatically, in this case, 3.3.0-SNAPSHOT.

https://docs.micronaut.io/latest/guide/index.html#usingsnapshots

**Comment by StephanePaulus** [comment]
@alvarosanchez just a heads up, or maybe I am doing somehting wrong, but the path changed. That is why it wasn't working for me before. 
io.micronaut.configuration:micronaut-micrometer-registry-new-relic-telemetry:${micronaut.version} <- Does not work
io.micronaut.micrometer:micronaut-micrometer-registry-new-relic-telemetry <- Does work. 

So maybe a hot fix is needed for the guide documentation.

**Comment by alvarosanchez** [comment]
The group id was changed a few minor versions ago IIRC, and in https://micronaut-projects.github.io/micronaut-micrometer/latest/guide/#_configuration I see it correctly.

If you spotted `io.micronaut.configuration` group id being used somewhere else in the docs, we would appreciate a PR with the update.

**Comment by StephanePaulus** [comment]
You can include the New Relic Telemetry reporter via `io.micronaut.configuration:micronaut-micrometer-registry-new-relic-telemetry:${micronaut.version}`

dependency:micronaut-micrometer-registry-new-relic-telemetry[groupId="io.micronaut.micrometer"]

Should these 2 be consistent or not? I see now this is for all the documentation in micrometer.

**Comment by alvarosanchez** [comment]
Fair enough, I have created #225 to not forget about it

**Comment by alvarosanchez** [comment]
And to answer your question, yes, they should be consistent and point to `io.micronaut.micrometer`.

**Pull request merged**
