### PR TITLE
Add Netty's channel metrics

### PR DESCRIPTION
**Pull request by croudet**

### CODE REVIEW

**Comment by croudet** [comment]
No test is run. There must be something missing in the build scripts.

**Comment by graemerocher** [comment]
Yes seems to be the update to spock 2.0.. one sec

**Comment by graemerocher** [comment]
What branch is this targeting?

**Comment by graemerocher** [comment]
Think it should be master

**Comment by croudet** [comment]
It depends on micronaut-core 2.x for the pipeline customizer. Master currently targets 1.3.5.
That's why I used micronaut-2.x branch as base.

**Comment by graemerocher** [comment]
Ok, I understand. We are trying to close out the 2.0.0 release in the next few weeks so this PR will have to wait until 2.0.0 GA. Thanks for the contribution however.

**Comment by croudet** [comment]
Replaces by https://github.com/micronaut-projects/micronaut-micrometer/pull/93

**Pull request closed without merging**
