### PR TITLE
build: bump up to Micronaut 3.5.3

### PR DESCRIPTION
**Pull request by sdelamo**

### CODE REVIEW

**Comment by sdelamo** [comment]
can you check this? It seems we cannot resolve `grpc-api`

**Comment by timyates** [comment]
@melix I cannot see how there used to be a `compileOnly libs.grpc.api` catalog dependency in 3.4.x, but now there isn't one, do you have any ideas what's gone wrong?

**Comment by melix** [comment]
There is clearly no `grpc-api` in previous versions of the catalog, but this isn't the problem: `libs.grpc.api` is defined in this project: https://github.com/micronaut-projects/micronaut-micrometer/blob/master/gradle/libs.versions.toml#L16

The reason it fails is because there's no associated version now. Which means, that the new BOM doesn't provide such a version, which also means it was a breaking change that we should have noticed. The new "BOM compatibility" checks should capture some of those problems. In the meantime it means you either have to import a BOM which provides the version for the grpc lib, or add it explicitly in the catalog.

**Comment by timyates** [comment]
@melix ahh, is it because we removed `boms-grpc = { module = "io.grpc:grpc-bom", version.ref = "managed-grpc" }` from core?

Is there a way to get the version of GRPC into this module without adding `managed-grpc` in to the catalog here that shadows the one in the grpc module?

**Comment by melix** [comment]
>  is it because we removed boms-grpc = { module = "io.grpc:grpc-bom", version.ref = "managed-grpc" } from core?

Very likely!

> Is there a way to get the version of GRPC into this module without adding managed-grpc in to the catalog here that shadows the one in the grpc module?

I'm not sure I understand the question. You can get the version by importing the grpc bom. You don't need to add it as a managed dependency. You can simply declare the dependency and use it as a `platform(libs.grpc.bom)`

**Comment by timyates** [comment]
> I'm not sure I understand the question. You can get the version by importing the grpc bom. You don't need to add it as a managed dependency. You can simply declare the dependency and use it as a `platform(libs.grpc.bom)`

Yes, but we would need to declare the version here?

And then keep it in line with https://github.com/micronaut-projects/micronaut-grpc ?

**Comment by melix** [comment]
Ah yes, you need to provide the version of the BOM, until we restore its import in the Micronaut BOM.

**Comment by timyates** [comment]
Done in https://github.com/micronaut-projects/micronaut-micrometer/pull/425/commits/27766db2d82feb82a79b6e312eb683e41b272272

**Comment by timyates** [comment]
How can we restore the `boms-grpc` line in the core catalog, but **not** require a `grpc` version in the core catalog?

Could we put the `boms-grpc` in the grpc module?  Would that filter down into the core bom?

**Comment by melix** [comment]
You would need a grpc version. Why would you want to remove it (sorry discovering problems as they go)?

**Comment by melix** [comment]
Then shouldn't Micronaut GRPC _import_ the grpc BOM? e.g `boms-grpc` in the Micronaut GRPC project?

**Comment by timyates** [comment]
I'll try that locally, and see if it works 🤞

**Pull request merged**
