### PR TITLE
Add support for LoggingMeterRegistry

### PR DESCRIPTION
**Pull request by croudet**
Gives to ability to dump the metrics in the logs.
For instance for logback add the following logger in logback.xml:

    <logger name="io.micrometer.core.instrument.logging.LoggingMeterRegistry"
            additivity="false" level="info">
            <appender-ref ref="metricsAppender" />
    </logger>

### CODE REVIEW

**Comment by graemerocher** [comment]
@croudet Thanks for the PR, do you think a new module is needed it could it just be included in `micronaut-micrometer-core`

**Comment by croudet** [comment]
I guess it can be included in `micronaut-micrometer-core`, it is the way it is done in `micrometer`:
https://github.com/micrometer-metrics/micrometer/tree/master/micrometer-core/src/main/java/io/micrometer/core/instrument/logging

**Comment by graemerocher** [comment]
Would you update the PR for this change?

**Comment by croudet** [comment]
Sure.

**Comment by graemerocher** [comment]
Thanks for the PR!

**Pull request merged**
