### PR TITLE
Remove duplicated versions

### PR DESCRIPTION
**Pull request by alvarosanchez**
Follow-up of #187

### CODE REVIEW

**Review by ilopmar — CHANGES_REQUESTED** [review]
I still see the following duplicates:

image

image


image

**Comment by alvarosanchez** [comment]
It's not feasible to fix those. Many are about dependencies used in test scopes. Others would need us to fix what versions are used of, eg, Apache HTTP Client, through all the dependencies tree. What version would you set it to? How can you be sure that whoever is using 4.4.x will still work with 4.5.x?

If you were to do this exercise on any other module, you would be surprised by how many duplicated dependencies there are.

**Review by ilopmar — APPROVED** [review]
:+1:

**Comment by alvarosanchez** [comment]
Based on my last comment, I think it's risky to mess with third-party dependencies, and we should only do it reacting to an issue request.

Closing this.

**Pull request closed without merging**
